language: go
go:
- 1.3
- 1.4
- tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
install:
- export GOPATH="$HOME/gopath"
- mkdir -p "$GOPATH/src/sevki.org/"
- mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/sevki.org/joker"
- go get -v -t -d sevki.org/joker/...
script:
- go test -v sevki.org/joker/...
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
