language: go

go:
  - 1.3
  - 1.4

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/sevki.org/"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/sevki.org/joker"
  - go get -v -t -d sevki.org/joker/...

script:
  - go test -v sevki.org/joker/...
